# Generated by Django 4.2.1 on 2023-06-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='published_by',
            field=models.CharField(default='N/A', max_length=64),
        ),
    ]
