# Generated by Django 4.2.3 on 2023-07-09 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_watchlist_listing_remove_watchlist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_listing',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bid_listing', to='auctions.auctionlisting'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bid_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
