# Generated by Django 4.2.3 on 2023-07-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_bid_bid_listing_bid_bid_user_comment_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
